services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    # ports:
      # - "8080:8080"
    env_file:
      - ./server/.env
    restart: unless-stopped

    # Allows interactive input
    stdin_open: true
    tty: true